site_title = "MyArxiv"
limit_days = 7
cache_url = "https://neuerliu.github.io/my_arxiv_paper/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "math.OC"
title = "Optimization and Control"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
